### ISSUE TITLE
Replicating generated examples

### ISSUE THREAD

**Issue by rorygraves** [harrah/browse#21]
Hi Mark,

I was playing with SXR (cool project btw) and was fiddling with the html to improve the look and feel.  you can see my current state here: https://github.com/rorygraves/browse  (basically it displays the code in an iframe within the index page (similar to scaladoc) for easier navigation.  This is definitely a work in progress.  

My question arises when I tried to replicate your examples, specifically scala compiler and library.  when I run against the locally compiled jar (I checked out the scala trunk and switched to v2.10.3 tag and ra:

```
ant -Dscalac.args=\"-Xplugin:/workspace/browse/target/scala-2.10/sxr_2.10-0.3.1-SNAPSHOT.jar  -P:sxr:base-directory:src/library\" quick.lib
```

I get a 

```
[quick.library] uncaught exception during compilation: java.lang.NoSuchMethodError
[quick.library] error: java.lang.NoSuchMethodError: scala.Predef$ArrowAssoc$.$minus$greater$extension(Ljava/lang/Object;Ljava/lang/Object;)Lscala/Tuple2;
[quick.library]     at sxr.Browse$$anonfun$topLevelMappings$1$$anonfun$apply$4$$anonfun$apply$5.apply(Browse.scala:102)
```

From my google searches this appears to be related to incompatible versions of 2.10 but I'm struggling to work it out right now.

Do you have any hints, or any scripts for the generation?

Setup:
  Mac - osX 10.9.1
  ant version: 1.9.3
  java version: 1.7.0_45
  sbt version: 0.13.0

Thanks for any input

Rory

**Comment by harrah** [comment]
Cool, thanks.  I made a couple of comments on the latest commit.

As for the examples, if you are referring to http://harrah.github.io/browse/samples/index.html, I think those haven't been regenerated in a while.  It does look like there is something incompatible with the different 2.10 versions.  If it is limited to the use of `->` for creating tuples, you might try to remove those from sxr as a workaround.  Otherwise, you might compile sxr using the exact local Scala version you are trying to run it against.

**Comment by rorygraves** [comment]
Thats a useful hint - I will have a further play.

**Comment by harrah** [comment]
It doesn't look like a problem with Scala.  You can run:

```
javap -classpath scala-library.jar 'scala.Predef$ArrowAssoc$'
```

and see that the expected method is there in 2.10.3.  I don't think I used ant when I generated the examples.  I probably just passed the sources to scalac.
